# Generated by Django 5.0.6 on 2024-07-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected'), (3, 'Pending HR Approval')], default='pending', max_length=20),
        ),
    ]
