# Generated by Django 5.0.6 on 2024-07-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_alter_leave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.IntegerField(),
        ),
    ]
